## How to use?

### - To access NumPy and its function in jupyter notebook import it in Python code like:

In [1]:
import numpy as np

### For python in VS Code write this in terminal and enter

###  pip install numpy

---

### How it looks like?

##### >>> a = np.arange(6)
##### >>> a2 = a[np.newaxis, :]
##### >>> a2.shape
(1,6)

### Three types of Arrays
###   1-D Array
###     2-D Array
###       3-D  Array

In [2]:
# 1-D array
import numpy as np
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
b = np.zeros(3)
b

array([0., 0., 0.])

In [4]:
c = np.ones(4)
c

array([1., 1., 1., 1.])

In [5]:
# These values are variyng depends on the number given in barckets
d = np.empty(3)
d

array([0., 0., 0.])

In [6]:
# with range of elements
e = np.arange(6)
e

array([0, 1, 2, 3, 4, 5])

In [7]:
# with sepcific range of elements
f = np.arange(2, 20)
f

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [8]:
# continue
g = np.arange(2, 20, 2) # the last 2 in parenthesis means with interval of two like 2, 4.....
g

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
# linerly spaced arrays
h = np.linspace(0, 10, num=5) # gives use 5 nums
h

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [10]:
# specific data types in array
i = np.ones(5, dtype=np.int8) # google int8
i

array([1, 1, 1, 1, 1], dtype=int8)

In [11]:
j = np.ones(3, dtype=np.float64)
j

array([1., 1., 1.])

---

#### 2-D Arrays

In [12]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

---

#### 3-D Arrays

In [20]:
# making and reshaping a 3D array
c= np.arange(24). reshape(3,2,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [21]:
d= np.arange(24). reshape(4,3,2)
d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [22]:
e= np.arange(24). reshape(2,4,3)
e

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [23]:
f= np.arange(24). reshape(3,4,2)
f

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [25]:
g= np.arange(24). reshape(4,2,3)
g

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [26]:
h = np.arange(24). reshape(2,3,4)
h

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])